export const ESTADOS_MEXICO = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Ciudad de México',
  'Coahuila',
  'Colima',
  'Durango',
  'Estado de México',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'Michoacán',
  'Morelos',
  'Nayarit',
  'Nuevo León',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana Roo',
  'San Luis Potosí',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz',
  'Yucatán',
  'Zacatecas',
] as const;

export type EstadoMexico = (typeof ESTADOS_MEXICO)[number];

export const CIUDADES_POR_ESTADO: Record<string, string[]> = {
  Aguascalientes: ['Aguascalientes', 'Calvillo', 'Pabellón de Arteaga', 'Rincón de Romos'],
  'Baja California': ['Tijuana', 'Mexicali', 'Ensenada', 'Tecate', 'Playas de Rosarito'],
  'Baja California Sur': ['La Paz', 'Los Cabos', 'Loreto', 'Mulegé'],
  Campeche: ['Campeche', 'Ciudad del Carmen', 'Champotón', 'Calkiní'],
  Chiapas: ['Tuxtla Gutiérrez', 'San Cristóbal de las Casas', 'Tapachula', 'Comitán', 'Palenque'],
  Chihuahua: ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Cuauhtémoc', 'Hidalgo del Parral'],
  'Ciudad de México': [
    'Álvaro Obregón',
    'Azcapotzalco',
    'Benito Juárez',
    'Coyoacán',
    'Cuajimalpa',
    'Cuauhtémoc',
    'Gustavo A. Madero',
    'Iztacalco',
    'Iztapalapa',
    'Magdalena Contreras',
    'Miguel Hidalgo',
    'Milpa Alta',
    'Tláhuac',
    'Tlalpan',
    'Venustiano Carranza',
    'Xochimilco',
  ],
  Coahuila: ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras', 'Acuña'],
  Colima: ['Colima', 'Manzanillo', 'Tecomán', 'Villa de Álvarez'],
  Durango: ['Durango', 'Gómez Palacio', 'Lerdo', 'Santiago Papasquiaro'],
  'Estado de México': [
    'Ecatepec',
    'Nezahualcóyotl',
    'Toluca',
    'Naucalpan',
    'Tlalnepantla',
    'Chimalhuacán',
    'Cuautitlán Izcalli',
    'Texcoco',
    'Atizapán de Zaragoza',
    'Tultitlán',
  ],
  Guanajuato: ['León', 'Guanajuato', 'Irapuato', 'Celaya', 'Salamanca', 'San Miguel de Allende'],
  Guerrero: ['Acapulco', 'Chilpancingo', 'Iguala', 'Zihuatanejo', 'Taxco'],
  Hidalgo: ['Pachuca', 'Tulancingo', 'Tula de Allende', 'Ixmiquilpan'],
  Jalisco: ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tonalá', 'Tlajomulco', 'Puerto Vallarta', 'Lagos de Moreno'],
  Michoacán: ['Morelia', 'Uruapan', 'Zamora', 'Lázaro Cárdenas', 'Apatzingán'],
  Morelos: ['Cuernavaca', 'Jiutepec', 'Cuautla', 'Temixco', 'Yautepec'],
  Nayarit: ['Tepic', 'Bahía de Banderas', 'Compostela', 'Santiago Ixcuintla'],
  'Nuevo León': [
    'Monterrey',
    'Guadalupe',
    'San Nicolás de los Garza',
    'Apodaca',
    'General Escobedo',
    'Santa Catarina',
    'San Pedro Garza García',
  ],
  Oaxaca: ['Oaxaca de Juárez', 'Salina Cruz', 'Juchitán de Zaragoza', 'Tuxtepec', 'Huajuapan de León'],
  Puebla: ['Puebla', 'Tehuacán', 'San Martín Texmelucan', 'Atlixco', 'San Andrés Cholula'],
  Querétaro: ['Querétaro', 'San Juan del Río', 'Corregidora', 'El Marqués'],
  'Quintana Roo': ['Cancún', 'Playa del Carmen', 'Chetumal', 'Tulum', 'Cozumel', 'Isla Mujeres'],
  'San Luis Potosí': ['San Luis Potosí', 'Ciudad Valles', 'Matehuala', 'Soledad de Graciano Sánchez'],
  Sinaloa: ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guasave', 'Guamúchil'],
  Sonora: ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'San Luis Río Colorado', 'Navojoa'],
  Tabasco: ['Villahermosa', 'Cárdenas', 'Macuspana', 'Comalcalco'],
  Tamaulipas: ['Reynosa', 'Matamoros', 'Nuevo Laredo', 'Tampico', 'Victoria', 'Altamira'],
  Tlaxcala: ['Tlaxcala', 'Apizaco', 'Huamantla', 'Chiautempan'],
  Veracruz: ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Córdoba', 'Orizaba', 'Poza Rica', 'Tuxpan'],
  Yucatán: ['Mérida', 'Valladolid', 'Progreso', 'Tizimín', 'Umán'],
  Zacatecas: ['Zacatecas', 'Guadalupe', 'Fresnillo', 'Jerez', 'Loreto'],
};
